enum ConfigKey {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  VERSION = 'VERSION',
  APP_GLOBAL_PREFIX = 'APP_GLOBAL_PREFIX',
  MONGO_DATABASE_CONNECTION_STRING = 'MONGO_DATABASE_CONNECTION_STRING',

  // Swagger
  SWAGGER_ENABLED = 'SWAGGER_ENABLED',
}

export default ConfigKey;
